stateDiagram-v2
    [*] --> Program
    Program --> Statement : EOF not reached
    Statement --> Declaration : TYPE
    Statement --> Assignment : IDENTIFIER
    Statement --> Input : input
    Statement --> Output : print
    Statement --> While : while
    Statement --> For : for
    Statement --> If : if
    Statement --> Block : {
    
    Declaration --> [*] : ;
    Assignment --> [*] : ;
    Input --> [*] : ;
    Output --> [*] : ;
    While --> Statement : body
    For --> Statement : body
    If --> Statement : then_branch
    Block --> Statement : } not reached
